modules:
  - id: "sailboat_rotation"
    type: "sensor"
  - id: "wind_direction"
    type: "sensor"
  - id: "rudder_rotation"
    type: "sensor"
  - id: "sailboat_position_x"
    type: "sensor"
  - id: "sailboat_position_y"
    type: "sensor"